check

diff --git a/examples/build-your-own-image/Dockerfile-windows b/examples/build-your-own-image/Dockerfile-windows
--- a/examples/build-your-own-image/Dockerfile-windows
+++ b/examples/build-your-own-image/Dockerfile-windows
@@ -40,14 +40,14 @@ RUN setx PATH \"%PATH%;C:\\Program Files\\National Instruments\\NI Package Manag
 SHELL ["cmd", "/S", "/C"]
 RUN nipkg feed-add --name=LV%LV_YEAR% %LV_FEED_LOCATION% && \
     nipkg feed-update && \
-    nipkg install --accept-eulas -y ni-offline-help-viewer || exit /b 0 && \
-    nipkg install --accept-eulas -y ni-labview-%LV_YEAR%-core-en || exit /b 0 && \
-    nipkg install --accept-eulas -y ni-viawin-labview-support || exit /b 0 && \
-    nipkg install --accept-eulas -y ni-labview-command-line-interface-x86 || exit /b 0 && \
+    nipkg install --accept-eulas -y ni-offline-help-viewer        || echo "ni-offline-help-viewer failed (ignored)" && \
+    nipkg install --accept-eulas -y ni-labview-%LV_YEAR%-core-en  || echo "ni-labview-core failed (ignored)" && \
+    nipkg install --accept-eulas -y ni-viawin-labview-support     || echo "ni-viawin-labview-support failed (ignored)" && \
+    nipkg install --accept-eulas -y ni-labview-command-line-interface-x86 || echo "CLI install failed (ignored)" && \
     nipkg feed-remove LV%LV_YEAR% && \
     nipkg feed-update && \
-    rmdir /S /Q "C:\ProgramData\National Instruments\NI Package Manager\packages"
-
+    rmdir /S /Q "C:\ProgramData\National Instruments\NI Package Manager\packages" || echo "cleanup failed (ignored)" && \
+    exit /b 0
 # Enable VI Server and cleaup resources folder
 RUN move C:\\ni\\resources\\LabVIEW.ini "C:\\Program Files\\National Instruments\\LabVIEW %LV_YEAR%\\LabVIEW.ini" && \
     rmdir /S /Q "C:\ni\resources"
